apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: demo
  annotations:
    nginx.org/ssl-services: "api,vuejs"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://api.demo-elyte.test", "http://demo-elyte.test", "http://*.demo-elyte.test", "http://localhost:8081", "http://demo-elyte.test", "http://demo-elyte.test:3001", "https://localhost:8081", "https://demo-elyte.test:443", "https://demo-elyte.test:4001"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - '*.demo-elyte.test'
        - demo-elyte.test
        - api.demo-elyte.test
      secretName: tls-secret
  rules:
  - host: api.demo-elyte.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8081
  
  - host: demo-elyte.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vuejs
            port:
              number: 8081
