apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-vuejs-ingress
  namespace: demo
  annotations:
    nginx.org/ssl-services: "api,vuejs"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS,DELETE"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://demo-elyte.test, http://*.demo-elyte.test"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - '*.demo-elyte.test'
        - demo-elyte.test
        - api.demo-elyte.test
      secretName: tls-secret
  rules:
    - host: api.demo-elyte.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8081
  
    - host: demo-elyte.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vuejs
                port:
                  number: 8081