version: '3.8'
networks:
  elyte_net:


services:
  db:
    image: mariadb
    container_name: maria-db
    restart: always
    expose:
      - "3306"
    env_file:
      - api.env
    volumes:
      # folder to hold the actual db data
      - ./persistence:/var/lib/mysql
    networks:
      - elyte_net

  api:
    container_name: fast-api
    image: fast-api
    build:
      context: ./api/src
      dockerfile: ./backend.dockerfile
    networks:
      - elyte_net
    ports:
      # <Port exposed> : < Port running inside container>
      - "8000:8000"
    depends_on:
      - db
      #- rabbitQ
    links:
      - db
      #- rabbitQ
    env_file:
      - api.env
    volumes:
      - ./api/src:/home

  frontend:
    container_name: vue-app
    image: vue-app
    build:
      context: ./vuejs3
      dockerfile: ./frontend.dockerfile
    networks:
      - elyte_net
    env_file:
      - ./vuejs3/frontend/.env
    ports:
      - 9000:8000
    
  # rabbitQ:
  #   hostname: rabbitQ
  #   image: rabbitmq:3-management
  #   container_name: rabbit
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   networks:
  #     - elyte_net

  # worker:
  #   image: worker
  #   container_name: main-worker
  #   build:
  #     context: ./api/src
  #     dockerfile: ./rabbitworker.dockerfile
  #   restart: always
  #   env_file:
  #     - api.env
  #   networks:
  #     - elyte_net
  #   volumes:
  #     - ./api/src:/usr/src
  #   links:
  #     - db
  #     - rabbitQ
