version: '3.8'
networks:
  elyte_net:


services:
  db:
    image: mariadb
    container_name: maria-db
    restart: always
    env_file:
      - api.env
    ports:
      - "3306:3306"
    volumes:
      # folder to hold the actual db data
      - ./persistence:/var/lib/mysql
    networks:
      - elyte_net

  api:
    container_name: fast-api
    image: fast-api
    platform: linux/amd64 # <- Only one working for Apple M1
    build:
      context: ./api
      dockerfile: ./backend.dev.dockerfile

    networks:
      - elyte_net
    ports:
      # <Port exposed> : < Port running inside container>
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
      #- rabbitQ
    links:
      - db
      #- rabbitQ
    env_file:
      - api.env
    volumes:
      - ./api/src:/code/app

  frontend:
    container_name: vue-app
    image: vue-app
    build:
      context: ./e-commerce
      dockerfile: ./frontend.dockerfile
    networks:
      - elyte_net
    env_file:
      - ./e-commerce/.env
    ports:
      - 9000:8000
    depends_on:
      - api

  rabbitQ:
    hostname: rabbitQ
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure
    networks:
      - elyte_net

  worker:
    image: worker
    container_name: main-worker
    build:
      context: ./api/src
      dockerfile: ./rabbitworker.dockerfile
    restart: always
    env_file:
      - api.env
    networks:
      - elyte_net
    volumes:
      - ./api/src:/usr/src
    links:
      - db
      - rabbitQ
