FROM --platform=linux/amd64 python:3.10.0

# Copy only requirements to cache them in docker layer:
WORKDIR /usr/src


COPY [ "./src/", "./"]

# Set the python path:
ENV PYTHONPATH="$PYTHONPATH:${PWD}"

RUN pip install --upgrade pip && pip install poetry==1.1.12

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-root --no-dev

CMD ["python", "-u", "run_worker.py"]
