apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  template:
    metadata:
      labels:
        name: db
    spec:   
      containers:
        - name: db
          image: mariadb
          ports:
            - containerPort: 3306 
          env:
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "1" # if it is 1 and root_password is set, root_password takes precedance
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MYSQL_ROOT_PASSWORD
---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: demo
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: db
  
