apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vue-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  tls:
    - hosts:
        - elyte.info
      secretName: tls-secret
   
  rules:
  - host: elyte.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vuejs
            port:
              number: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vuejs
  template:
    metadata:
      labels:
        name: vuejs
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: vuejs
          imagePullPolicy: IfNotPresent
          image: elyte5star/vuej3:v1 
          ports:
            - containerPort: 8000
          env:
            - name: VUE_API_URL
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: VUE_API_URL

            - name: VUE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: dashboard-secrets
                  key: VUE_BASE_URL

            - name: VITE_APP_WAIT_TIME
              valueFrom:
                secretKeyRef:
                  name: dashboard-secrets
                  key: VITE_APP_WAIT_TIME

            - name: VUE_MAINTENANCE_MODE
              valueFrom:
                secretKeyRef:
                  name: dashboard-secrets
                  key: VUE_MAINTENANCE_MODE


            - name: VITE_APP_MSAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dashboard-secrets
                  key: VITE_APP_MSAL_CLIENT_ID

            - name: VUE_APP_MSAL_LOGIN_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: dashboard-secrets
                  key: VUE_APP_MSAL_LOGIN_AUTHORITY
            
            - name: VUE_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dashboard-secrets
                  key: VUE_GOOGLE_CLIENT_ID
            
            - name: NGINX_PROXY_PASS
              valueFrom:
                secretKeyRef:
                  name: dashboard-secrets
                  key: NGINX_PROXY_PASS

            - name: NGINX_PORT
              valueFrom:
                secretKeyRef:
                  name: dashboard-secrets
                  key: NGINX_PORT