apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitQ
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_peer_discovery_k8s
    additionalConfig: |
            log.console.level = info
            channel_max = 700
            default_user= guest 
            default_pass = guest
            queue_master_locator = min-masters
            loopback_users.guest = false
  service:
    type: LoadBalancer