apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker
  template:
    metadata:
      labels:
        name: worker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
          image: elyte5star/worker:v1 
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MYSQL_ROOT_PASSWORD

            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MYSQL_USER

            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MYSQL_ROOT_PASSWORD
            
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MYSQL_DATABASE
            
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: MYSQL_HOST