
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-cluster-default-user
  namespace: demo
stringData:
  default_user.conf: |
    default_user = rabbitUser
    default_pass = elyteRQ
  password: elyteRQ # this line is only necessary if you also use messaging topology operator
  username: rabbitUser 
  
---

# apiVersion: rabbitmq.com/v1beta1
# kind: User
# metadata:
#   name: rabbit-user
#   namespace: demo
# spec:
#   tags:
#     - management 
#     - policymaker
#     - monitoring
#     - administrator
#   rabbitmqClusterReference:
#     name: rabbitmq-cluster # rabbitmqCluster must exist in the same namespace as this resource
#   importCredentialsSecret:
#     name: rabbitmq-cluster-default-user


# ---

# apiVersion: rabbitmq.com/v1beta1
# kind: Permission
# metadata:
#   name: rabbit-user-permission
#   namespace: demo
# spec:
#   vhost: "/"
#   user: "rabbitUser" # name of the RabbitMQ user
#   permissions:
#     write: ".*"
#     configure: ".*"
#     read: ".*"
#   rabbitmqClusterReference:
#     name: rabbitmq-cluster
