apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: demo
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_peer_discovery_k8s
    additionalConfig: |
            log.console.level = info
            channel_max = 200
            disk_free_limit.relative = 1.5
            management.path_prefix = /rabbitmq
            vm_memory_high_watermark.relative = 0.7
            vm_memory_high_watermark_paging_ratio = 0.9
  service:
    type: LoadBalancer