apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: maria-hostpath
  namespace: demo
provisioner: microk8s.io/hostpath
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---

#a PVC (Persistent Volume Claim) to PV (Persistent Volume) 
#binding is a one-to-one mapping, 
#using a ClaimRef which is a bi-directional binding between
#the PersistentVolume and the PersistentVolumeClaim.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: maria-pv
  namespace: demo
  labels:
    type: local
spec:
  storageClassName: maria-hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/maria/data"
    

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-pvc
  namespace: demo
spec:
  storageClassName: maria-hostpath
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 3Gi } }

  
