kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd-hostpath
  namespace: demo
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /mnt/ssd-disk
volumeBindingMode: WaitForFirstConsumer


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-pvc
  namespace: demo
spec:
  accessModes: [ReadWriteMany]
  resources: { requests: { storage: 5Gi } }
