# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: standard
#   namespace: demo
# provisioner: k8s.io/minikube-hostpath
# reclaimPolicy: Delete
# parameters:
#   pvDir: /mnt/ssd-disk
# volumeBindingMode: WaitForFirstConsumer


# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-pvc
  namespace: demo
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 5Gi } }
  storageClassName: csi-hostpath-sc
  
