apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: maria-hostpath
  namespace: demo
provisioner: microk8s.io/hostpath
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: maria-pv
  namespace: demo
  labels:
    type: local
spec:
  storageClassName: base
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/maria/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-pvc
  namespace: demo
spec:
  storageClassName: base
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 3Gi } }

  
