apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60